#!/usr/bin/env python3
"""Harvest the workspace into the brain: walk every project in the parent
workspace dir, mine its docs (README / CLAUDE.md / HANDOFF / notes) for what
it is, its stack, and its patterns, and write one sourced, freshness-stamped
knowledge card per project into the vault at Maestro/Knowledge/ (+ an _index
MOC). Cards are wikilinked so the brain graph clusters them.

No naked facts: every card carries `source:` (the real file paths) and
`harvested:` (date). Re-running refreshes cards in place.

Usage: python memory/harvest.py [workspace-dir]
"""
import datetime
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
from pipeline import vault_path

DOCS = ("README.md", "CLAUDE.md", "HANDOFF.md", "NOTES.md", "ARCHITECTURE.md")
STACK = {"pyproject.toml": "python", "requirements.txt": "python",
         "package.json": "node", "Cargo.toml": "rust", "go.mod": "go",
         "platformio.ini": "embedded", "CMakeLists.txt": "c/c++",
         ".mcp.json": "mcp", ".claude": "claude-code"}
SKIP = {"node_modules", "__pycache__", ".git", "venv", ".venv", "uploads", "New folder"}


def first_para(text):
    for block in re.split(r"\n\s*\n", text):
        block = block.strip()
        if block and not block.startswith(("#", "<", "---", "[", "!", "```")):
            return re.sub(r"\s+", " ", block)[:400]
    return ""


def headings(text, cap=12):
    hs = [h.strip() for h in re.findall(r"^#{2,3}\s+(.+)$", text, re.M)]
    return hs[:cap]


def mine(pdir):
    info = {"docs": [], "para": "", "heads": [], "stack": set(), "claude": False}
    try:
        entries = os.listdir(pdir)
    except OSError:
        return info
    for marker, tech in STACK.items():
        if marker in entries:
            info["stack"].add(tech)
    for dn in DOCS:
        fp = os.path.join(pdir, dn)
        if not os.path.isfile(fp):
            fp = os.path.join(pdir, "docs", dn)
            if not os.path.isfile(fp):
                continue
        try:
            txt = open(fp, encoding="utf-8", errors="ignore").read(40000)
        except OSError:
            continue
        info["docs"].append(os.path.relpath(fp, pdir).replace("\\", "/"))
        if not info["para"]:
            info["para"] = first_para(txt)
        info["heads"] += [h for h in headings(txt) if h not in info["heads"]]
    info["heads"] = info["heads"][:14]
    return info


def main():
    ws = sys.argv[1] if len(sys.argv) > 1 else os.path.dirname(ROOT)
    vp = vault_path()
    if not vp or not os.path.isdir(vp):
        print("no vault; aborting")
        return 1
    kdir = os.path.join(vp, "Maestro", "Knowledge")
    os.makedirs(kdir, exist_ok=True)
    today = datetime.datetime.now().date().isoformat()
    cards = []
    me = os.path.basename(ROOT)
    for name in sorted(os.listdir(ws)):
        pdir = os.path.join(ws, name)
        if not os.path.isdir(pdir) or name in SKIP or name.startswith("."):
            continue
        if os.path.realpath(pdir) == os.path.realpath(ROOT):
            continue  # the substrate doesn't document itself as a neighbor
        info = mine(pdir)
        if not info["docs"] and not info["stack"]:
            continue  # nothing sourced to say — no naked facts
        slug = re.sub(r"[^\w\-]", "-", name)
        lines = ["# %s" % name, ""]
        if info["para"]:
            lines += [info["para"], ""]
        if info["stack"]:
            lines += ["**Stack:** " + ", ".join(sorted(info["stack"])), ""]
        if info["heads"]:
            lines += ["**Patterns / topics in its docs:**"] + \
                     ["- " + h for h in info["heads"]] + [""]
        lines += ["Workspace neighbor of [[%s]]. See [[_index|Knowledge index]]." % me, "",
                  "---", "source: " + "; ".join(
                      os.path.join(name, d) for d in info["docs"]) if info["docs"]
                  else "source: directory markers only",
                  "harvested: " + today]
        with open(os.path.join(kdir, slug + ".md"), "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")
        cards.append((slug, name, info["para"][:90]))
        print("card: %s (%s docs, stack: %s)" % (
            name, len(info["docs"]), ",".join(sorted(info["stack"])) or "-"))
    ix = ["# Knowledge index", "",
          "What Maestro knows about the workspace around it. Auto-generated by",
          "`memory/harvest.py` — re-run it to refresh. harvested: " + today, ""]
    ix += ["- [[%s]] — %s" % (slug, blurb or nm) for slug, nm, blurb in cards]
    with open(os.path.join(kdir, "_index.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(ix) + "\n")
    print("%d cards -> %s" % (len(cards), kdir))
    return 0


if __name__ == "__main__":
    sys.exit(main())
